version: '3.5'

services:
  postgres:
    image: 'postgres:13-alpine'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
#  web:
#    build: .
#    image: laurielias/stefan:latest
#    #container_name: 'web'
#    #command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - 8000:8000 # Django
#    #environment:
#      #- APP_SECRET_KEY=moxqms%4zujsgd!c*y#36d!7#dh2e)+of-zla+)z9m09e)cvb%
#      #- APP_DB_PASSWORD=saladus
#      #- APP_DEBUG=1
#    depends_on:
#      - db